#!/bin/bash
cmsg=${1:-minor change on site}
git add .
git commit -m "$cmsg"
git push origin main 
ssh ec2-user@llamas.us.to -i ~/.ssh/danny.pem '
cd /home/ec2-user/Git/Personal-Website-NEW; 
git pull -ff;
cp -fr Production/finished/* /home/ec2-user/Live/;
rm /home/ec2-user/Live/Assets;
rm /home/ec2-user/Live/static/Assets;
ln -s Production/Assets /home/ec2-user/Live/static/Assets;
echo "=============================";
echo "     IN LIVE RIGHT NOW:";
echo "=============================";
find -L /home/ec2-user/Live ! -path *node_modules*;
echo "=============================";
sudo systemctl restart node.service;
'
