#!/bin/bash
cmsg=${1:-minor change on site}
git add .
git commit -m "$cmsg"
git push -ff origin main 
ssh  -y ubuntu@llamas.to 'mkdir -p ~/SSH';
sshfs ubuntu@llamas.to:/home/ubuntu/SSH ~/SSH
rm -fr ~/SSH/*
cp -vr ./Production/finished/* ~/SSH/
rm -fr ~/SSH/Assets
mkdir ~/SSH/Assets
cp -vf ./Production/Assets/* ~/SSH/Assets
ssh  -y ubuntu@llamas.to '
  cd /var/www/Personal_Static;
  sudo rm -fr ./*;
  sudo cp -vr ~/SSH/* ./;
  sudo rm ./server.js ./package-lock.json ./package.json;
  sudo cp ./static/* ./;
  sudo rmdir ./static; '
fusermount3 -u ~/SSH
